### PR TITLE
[Fix] performance issues related to DragEvents.

### LINKED ISSUE #1: initial
- [x] Handle Events
- [x] Fix Panning on over-scroll (zoom in/out)
- [x] Fix map controls
- [x] check that vector tiles works properly and configurable from dart (shouldn't be something special) 
- [x] fix stretch thing
- [ ] mobile zoom
- [x] check multiple sessions (2 or more map widgets at the same time) 
- [x] Map rendering
- [x] fix panic after disposing a map outside tokio runtime
```
thread 'tokio-runtime-worker' panicked at /home/dev/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/irondash_texture-0.5.0/src/lib.rs:263:49:
called `Result::unwrap()` on an `Err` value: WrongThread
stack backtrace:
``` 
- [x] Lints

### PR DESCRIPTION
**Pull request by shri-acha**
fixes #5

### CODE REVIEW

**Comment by shri-acha** [comment]
@nrbnlulu I'm not sure how we're monitoring the performance, but I've replaced how the rendering happens now it is more consistent with what @suzanpradhan expects.

**Comment by nrbnlulu** [comment]
attach a video, rendering 2 map widgets in parallel then dispose them and reinstantiate them.. 
while monitoring your pc resources..

File: lib/src/galileo_map_widget.dart [hunk 1]
```diff
@@ -648,6 +647,11 @@ class _GalileoMapWidgetState extends State<GalileoMapWidget> with SingleTickerPr
 
     super.dispose();
 
+    // Dispose focus node if we created it
+    if (widget.focusNode == null) {
+      _focusNode.dispose();
+    }
+
```
Comment (nrbnlulu) [inline lib/src/galileo_map_widget.dart]: nit: these lines were moved..

File: rust/src/core/map_session.rs [hunk 2]
```diff
@@ -275,11 +275,11 @@ impl MapSession {
             map.set_messenger(None::<DummyMessenger>);
             map.layers_mut().clear();
         }
-
         flctx
     }
 }
 /// Updates the session counter and returns a new session ID
 fn create_new_session() -> SessionID {
+    info!("Session created: {}", SESSION_COUNTER.load(Ordering::Relaxed));
```
Comment (nrbnlulu) [inline rust/src/core/map_session.rs]: log::debug

File: rust/src/core/pixel_buffer.rs [hunk 3]
```diff
@@ -163,15 +163,17 @@ impl PixelBuffer {
...
-        // Copy data to our internal buffer
-        let expected_size = (4 * self.size.width * self.size.height) as usize;
+        let expected_size = (4 * self.size.width * self.size.height) as usize; // 4 bytes / pixel
         if data.len() != expected_size {
+            drop(data);
+            staging_buffer.unmap();
             return Err(PixelBufferError::InvalidBufferSize {
                 width: self.size.width,
                 height: self.size.height,
             });
```
Comment (nrbnlulu) [inline rust/src/core/pixel_buffer.rs:173]: can u explain?

Comment (shri-acha) [reply rust/src/core/pixel_buffer.rs:173]: if not dropped the data and unmapping the buffer , the function returns without cleanup no?

File: lib/src/galileo_map_widget.dart (hunk 1 above)
Comment (shri-acha) [reply lib/src/galileo_map_widget.dart]: same reason as below.

**Comment by shri-acha** [comment]
@nrbnlulu  

https://github.com/user-attachments/assets/6328aa5b-3b03-4837-9b07-868795c78321

I believe this was the expected outcome right?

File: lib/src/galileo_map_widget.dart (hunk 1 above)
Comment (nrbnlulu) [reply lib/src/galileo_map_widget.dart]: ?

Comment (shri-acha) [reply lib/src/galileo_map_widget.dart]: nvm, i'm wrong here, i've pushed the changes with old order here.

**Comment by nrbnlulu** [comment]
## Code Review: `debounce` branch vs `main`

### 🔴 Critical Bugs & Safety

#### 1. **Rust Panics - Multiple `unwrap()` Calls**
**Location:** `rust/src/api/api.rs`, `rust/src/core/mod.rs`, `rust/src/core/map_session.rs`

**Issues:**
- `rust/src/api/api.rs:68` - `TOKIO_RUNTIME.get().unwrap()` in `create_new_map_session()`
- `rust/src/api/api.rs:83` - `TOKIO_RUNTIME.get().unwrap()` in `request_map_redraw()`
- `rust/src/api/api.rs:113` - `TOKIO_RUNTIME.get().unwrap()` in `destroy_session()`
- `rust/src/api/api.rs:139` - `TOKIO_RUNTIME.get().unwrap()` in `add_session_layer()` (multiple)
- `rust/src/api/api.rs:169` - `TOKIO_RUNTIME.get().unwrap()` in `get_map_viewport()`
- `rust/src/api/api.rs:217` - `TOKIO_RUNTIME.get().unwrap()` in `resize_session()`
- `rust/src/core/mod.rs:36` - `.build().unwrap()` in `TOKIO_RUNTIME` initialization
- `rust/src/core/mod.rs:73` - `.try_init().unwrap()` and `.lock().unwrap().replace(guard)`

**Fix Prompt:** *"Rewrite these Rust functions to return `Result<T, anyhow::Error>` instead of using `.unwrap()`, and ensure the Dart side handles the potential error. For the `TOKIO_RUNTIME` static, use `expect()` with descriptive messages or restructure to avoid panics."*

---

#### 2. **Clippy: `MutexGuard` Held Across Await Point**
**Location:** `rust/src/core/map_session.rs:246-255`

```rust
let flctx = self.flutter_ctx.read();  // RwLockReadGuard held here
// ...
flutter_ctx.payload_holder.resize(new_size);  // Used here
self.redraw().await?;  // ⚠️ Await while lock is held!
```

**Fix Prompt:** *"Clone the necessary data from `flutter_ctx` before the await point, or restructure to drop the `RwLockReadGuard` before calling `self.redraw().await`. Consider using `let ctx_data = { let flctx = self.flutter_ctx.read(); ... }; drop(flctx);` pattern."*

---

#### 3. **Clippy: Unhandled `Result` from `inspect_err()`**
**Location:** `rust/src/core/map_session.rs:261`

```rust
self.redraw().await.inspect_err(|err| error!("{err}"));
```

**Fix Prompt:** *"Add `let _ =` to explicitly acknowledge the unused Result, or better, propagate the error with `?` if the caller can handle it."*

---

### 🟡 Lints & Static Analysis

#### 4. **Clippy: Module Inception**
**Location:** `rust/src/api/mod.rs:1`

```rust
pub mod api;  // Module named 'api' inside 'api' directory
```

**Fix Prompt:** *"Rename `rust/src/api/api.rs` to `rust/src/api/mod.rs` and move its contents there, or rename the module to avoid the inception (e.g., `pub mod galileo_api;`)."*

---

#### 5. **Clippy: Let Underscore Future**
**Location:** `rust/src/api/api.rs:240`, `rust/src/core/map_session.rs:72`

```rust
let _ = runtime.spawn(async move { ... });
```

**Fix Prompt:** *"Replace `let _ = runtime.spawn(...)` with `std::mem::drop(runtime.spawn(...))` to explicitly acknowledge the intentional discard, or better, store the `JoinHandle` for potential cancellation."*

---

#### 6. **Dart: Immutable Widget with Non-Final Field**
**Location:** `lib/src/galileo_map_widget.dart:13, 38`

```dart
class GalileoMapWidget extends StatefulWidget {
  // ...
  late Future<(GalileoMapController?, String?)>? _controllerFuture;  // ⚠️ Not final
}
```

**Fix Prompt:** *"Move `_controllerFuture` to the State class (`_GalileoMapWidgetState`) since it's stateful data, or mark it as `final` if it should be immutable widget configuration."*

---

#### 7. **Dart: Unused Field and Variables**
**Location:** `lib/src/galileo_map_widget.dart`

- `_controllerFuture` (unused field in widget)
- `_isDragging` (unused field)
- `mouseEvent` (unused local variable in `onPointerUp`)

**Fix Prompt:** *"Remove unused field `_isDragging`. Move or remove `_controllerFuture`. Use or remove `mouseEvent` variable in the pointer handler."*

---

### 🟡 Code Smells

#### 8. **Duplicate Keyboard Event Handling**
**Location:** `lib/src/galileo_map_widget.dart:384-517`

The keyboard event handling for `KeyDownEvent` and `KeyRepeatEvent` has **identical code duplicated** (~130 lines).

**Fix Prompt:** *"Extract the keyboard navigation logic into a private method `_handleNavigationKey(LogicalKeyboardKey key)` and call it from both `KeyDownEvent` and `KeyRepeatEvent` handlers."*

---

#### 9. **Hardcoded Windows Font Path (Removed but Left Comment)**
**Location:** `rust/src/api/api.rs:44`

The original code had `service.load_fonts("C:/Windows/Fonts");` which was removed, but the `TODO` comment about custom fonts is also gone.

**Fix Prompt:** *"Add a cross-platform font initialization strategy. Consider using platform-specific paths or a font discovery mechanism for Linux, macOS, Windows, Android, and iOS."*

---

#### 10. **Magic Number in Throttle**
**Location:** `rust/src/core/map_session.rs:74`

```rust
tokio::time::sleep(Duration::from_millis(16)).await; // throttle to ~60fps
```

**Fix Prompt:** *"Extract `16` to a named constant like `const FRAME_THROTTLE_MS: u64 = 16;` with documentation about the 60fps target."*

---

### 🔵 DX (Developer Experience)

#### 11. **Missing Documentation on Public Functions**
**Location:** `rust/src/api/api.rs`

Several `pub fn` functions lack `///` doc comments:
- `set_tile_cache_path()`
- `create_new_map_session()` (has info log but no docs)
- `add_session_layer()`

**Fix Prompt:** *"Generate Dart-compatible doc comments for these Rust functions based on their logic and parameters. FRB will carry these over to Dart."*

---

#### 12. **Opaque Error Types**
**Location:** `rust/src/api/api.rs` - All functions return `anyhow::Result<()>`

**Fix Prompt:** *"Replace generic `anyhow::Error` with specific error enums (e.g., `GalileoError::SessionNotFound`, `GalileoError::RendererError`) for better pattern matching in Dart."*

---

### 🟡 UX & Performance

#### 13. **Blocking UI Thread - Synchronous `block_on()`**
**Location:** `rust/src/api/api.rs` - Multiple functions

All functions use `TOKIO_RUNTIME.get().unwrap().block_on(...)` which can block the platform thread.

**Fix Prompt:** *"Consider making these FRB functions `async` in Rust (using `#[frb(async)]`) to prevent blocking the Dart platform thread, especially for `create_new_map_session()` and `add_session_layer()`."*

---

#### 14. **First Render Artificial Delay**
**Location:** `rust/src/core/map_session.rs:175`

```rust
if is_first_render {
    tokio::time::sleep(Duration::from_millis(1000)).await;  // ⚠️ 1 second delay!
}
```

**Fix Prompt:** *"Document why this 1-second delay exists. If it's a workaround for initialization race conditions, fix the root cause instead of adding latency."*

---

#### 15. **Dart: Sort Child Properties Last**
**Location:** `lib/src/galileo_map_widget.dart:73`

```dart
GalileoMapWidget._({
  // ...
  Widget? child,  // Should be last
  // ...
})
```

**Fix Prompt:** *"Move the `child` parameter to the end of the constructor parameter list to follow Flutter conventions."*

---

### Summary Table

| # | Category | Priority | File | Issue |
|---|----------|----------|------|-------|
| 1 | Bugs | 🔴 | `api/api.rs`, `core/mod.rs` | Multiple `unwrap()` panics |
| 2 | Bugs | 🔴 | `map_session.rs:246` | RwLockGuard across await |
| 3 | Bugs | 🔴 | `map_session.rs:261` | Unhandled Result |
| 4 | Lints | 🟡 | `api/mod.rs` | Module inception |
| 5 | Lints | 🟡 | `api/api.rs`, `map_session.rs` | Let underscore future |
| 6 | Lints | 🟡 | `galileo_map_widget.dart` | Immutable widget violation |
| 7 | Lints | 🟡 | `galileo_map_widget.dart` | Unused fields/variables |
| 8 | Smells | 🟡 | `galileo_map_widget.dart` | Duplicate keyboard logic |
| 9 | Smells | 🟡 | `api/api.rs` | Missing cross-platform font strategy |
| 10 | Smells | 🟡 | `map_session.rs` | Magic number |
| 11 | DX | 🔵 | `api/api.rs` | Missing doc comments |
| 12 | DX | 🔵 | `api/api.rs` | Opaque error types |
| 13 | UX | 🟡 | `api/api.rs` | Blocking `block_on()` calls |
| 14 | UX | 🟡 | `map_session.rs` | Artificial 1s delay |
| 15 | UX | 🟡 | `galileo_map_widget.dart` | Child property order |

**Comment by shri-acha** [comment]
@nrbnlulu most lint errors are fixed now, and i'll work on the runtime one in another pr.

File: linux/flutter/ephemeral/generated_config.cmake [hunk 4]
```diff
@@ -0,0 +1,21 @@
...
+list(APPEND FLUTTER_TOOL_ENVIRONMENT
+  "FLUTTER_ROOT=/home/shri/flutter"
+  "PROJECT_DIR=/home/shri/.gitbuilds/galileo_flutter"
+  "DART_DEFINES=RkxVVFRFUl9WRVJTSU9OPTMuMzguOQ==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049NjczMjNkZTI4NQ==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049NTg3YzE4Zjg3Mw==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMC44"
+  "DART_OBFUSCATION=false"
+  "TRACK_WIDGET_CREATION=true"
+  "TREE_SHAKE_ICONS=false"
+  "PACKAGE_CONFIG=/home/shri/.gitbuilds/galileo_flutter/.dart_tool/package_config.json"
+  "FLUTTER_TARGET=/home/shri/.gitbuilds/galileo_flutter/example/lib/main.dart"
+)
```
[the remark this answers is not in the document]
Comment (nrbnlulu) [reply linux/flutter/ephemeral/generated_config.cmake]: true :upside_down_face:

File: Taskfile.yml [hunk 5]
```diff
@@ -18,16 +34,10 @@ tasks:
...
     dir: rust
     cmds:
-      - cargo clippy
-
-  rust.lint-fix:
-    desc: Automatically fix some Rust lint issues
-    dir: rust
-    cmds:
-      - cargo clippy --fix
+      - cargo check
```
[the remark this answers is not in the document]
Comment (nrbnlulu) [reply Taskfile.yml]: @shri-acha no idea whatsup with GH I can't commit directly.
put this in taskfile
```
version: "3"

vars:
    DART_BIN:
        sh: |
            if command -v fvm &> /dev/null; then
              echo "fvm dart"
            else
              echo "dart"
            fi
    FLUTTER_BIN:
        sh: |
            if command -v fvm &> /dev/null; then
              echo "fvm flutter"
            else
              echo "flutter"
            fi

tasks:
    # --- Rust tasks ---
    rust.fmt:
        desc: Format Rust code
        dir: rust
        cmds:
            - cargo fmt

    rust.fmt-check:
        desc: Check Rust code formatting
        dir: rust
        cmds:
            - cargo fmt -- --check

    rust.lint:
        desc: Lint Rust code
        dir: rust
        cmds:
            - cargo clippy -- -D warnings

    rust.check:
        desc: Check Rust compilation
        dir: rust
        cmds:
            - cargo check

    rust.test:
        desc: Run Rust tests
        dir: rust
        cmds:
            - cargo test

    rust.fix:
        desc: Fix Rust code issues where possible
        dir: rust
        cmds:
            - cargo clippy --fix --allow-dirty --allow-staged

    # --- Dart/Flutter tasks ---
    flutter.fmt:
        desc: Format Dart code
        cmds:
            - "{{.DART_BIN}} format ."

    flutter.fmt-check:
        desc: Check Dart code formatting
        cmds:
            - "{{.DART_BIN}} format --set-exit-if-changed ."

    flutter.lint:
        desc: Run Flutter analyzer
        cmds:
            - "{{.FLUTTER_BIN}} analyze ./example ./lib"

    flutter.fix:
        desc: Fix all Dart code issues and format
        cmds:
            - "{{.DART_BIN}} fix --apply"
            - "{{.DART_BIN}} format ."

    flutter.test:
        desc: Run Flutter tests
        cmds:
            - "{{.FLUTTER_BIN}} test"

    flutter.get:
        desc: Get Flutter dependencies
        cmds:
            - "{{.FLUTTER_BIN}} pub get"

    codegen:
        desc: generate rust bindings
        cmds:
            - rm -rf .dart_tool
            - flutter_rust_bridge_codegen generate

    # --- Combined tasks ---
    fix:
        desc: Fix both Rust and Flutter code issues
        deps:
            - task: rust.fix
            - task: flutter.fix

    fmt:
        desc: Format both Rust and Flutter code
        deps:
            - task: rust.fmt
            - task: flutter.fmt

    lint:
        desc: Lint both Rust and Flutter code
        deps:
            - task: rust.lint
            - task: flutter.lint

    check:
        desc: Check both Rust and Flutter code
        deps:
            - task: rust.check
            - task: flutter.lint

    test:
        desc: Run tests for both Rust and Flutter
        deps:
            - task: rust.test
            - task: flutter.test

    all:
        desc: Run format, lint, and test for both Rust and Flutter
        deps:
            - task: fmt
            - task: lint
            - task: test

```

**Comment by shri-acha** [comment]
i believe this does it =p, @nrbnlulu

**Comment by nrbnlulu** [comment]
thx!
